import fs from 'fs';
import path from 'path';

interface ParsedVaultQuest {
  id: string;
  title: string;
  giver: string;
  category: string;
  description: string;
  walkthrough: string[];
  rewards: string[];
  connections: string[];
  rawPath: string;
}

const VAULT_ROOT = path.resolve(process.cwd(), '../content/Sich_en');

function cleanWikiLink(link: string): string {
  // e.g. [[🧑Taras Chub]] -> taras_chub
  // e.g. [[🧑Ostap Vernydub|Ostap]] -> ostap_vernydub
  let text = link.replace(/[\[\]]/g, '').trim();
  if (text.includes('|')) {
    text = text.split('|')[0].trim();
  }
  // remove emojis
  text = text.replace(/[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu, '').trim();
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '_');
}

function parseMarkdownQuest(filePath: string): ParsedVaultQuest | null {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  let title = '';
  let giver = 'unknown';
  let category = 'side';
  let description = '';
  const walkthrough: string[] = [];
  const rewards: string[] = [];
  const connections: string[] = [];

  let currentSection = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (line.startsWith('# ')) {
      title = line.replace('#', '').replace(/[❔❓📃🏫]/g, '').trim();
      continue;
    }

    if (line.startsWith('## ')) {
      currentSection = line.replace('##', '').trim().toLowerCase();
      continue;
    }

    if (line.startsWith('### ')) {
      walkthrough.push(line.replace('###', '').trim());
      continue;
    }

    if (!line) continue;

    if (currentSection.includes('giver')) {
      const match = line.match(/\[\[(.*?)\]\]/);
      if (match) {
        giver = cleanWikiLink(match[1]);
      } else {
        giver = cleanWikiLink(line);
      }
    } else if (currentSection.includes('description')) {
      description += (description ? ' ' : '') + line.replace(/\[\[(.*?)\]\]/g, '$1').replace(/[*_]/g, '');
    } else if (currentSection.includes('walkthrough')) {
      if (line.startsWith('- ') || line.startsWith('* ')) {
        walkthrough.push(line.replace(/^[-*]\s+/, '').replace(/\[\[(.*?)\]\]/g, '$1'));
      }
    } else if (currentSection.includes('reward')) {
      if (line.startsWith('- ') || line.startsWith('* ')) {
        rewards.push(line.replace(/^[-*]\s+/, '').replace(/\[\[(.*?)\]\]/g, '$1'));
      }
    } else if (currentSection.includes('connection')) {
      if (line.includes('[[') && line.includes(']]')) {
        const matches = line.match(/\[\[(.*?)\]\]/g);
        if (matches) {
          matches.forEach((m) => connections.push(cleanWikiLink(m)));
        }
      }
    }
  }

  if (!title) {
    title = path.basename(filePath, '.md').replace(/[❔❓📃🏫]/g, '').trim();
  }

  const id = title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '_');

  return {
    id,
    title,
    giver,
    category,
    description,
    walkthrough,
    rewards,
    connections,
    rawPath: path.relative(VAULT_ROOT, filePath)
  };
}

function crawlDirectory(dir: string, fileList: string[] = []): string[] {
  if (!fs.existsSync(dir)) return fileList;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      crawlDirectory(fullPath, fileList);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

function main() {
  console.log(`[Quest Compiler] Scanning Obsidian Vault at: ${VAULT_ROOT}`);

  const questDirs = [
    path.join(VAULT_ROOT, 'Quests'),
    path.join(VAULT_ROOT, 'Factions/Ingulsk/Quests'),
    path.join(VAULT_ROOT, 'Factions/Ingulsk/Joining Quests')
  ];

  const allFiles: string[] = [];
  for (const qd of questDirs) {
    crawlDirectory(qd, allFiles);
  }

  console.log(`[Quest Compiler] Found ${allFiles.length} quest markdown files.`);

  const parsedQuests: Record<string, ParsedVaultQuest> = {};

  for (const f of allFiles) {
    const quest = parseMarkdownQuest(f);
    if (quest && quest.id) {
      parsedQuests[quest.id] = quest;
    }
  }

  const outJsonPath = path.resolve(process.cwd(), 'src/data/vaultQuests.json');
  fs.writeFileSync(outJsonPath, JSON.stringify(parsedQuests, null, 2), 'utf-8');
  console.log(`[Quest Compiler] Successfully wrote ${Object.keys(parsedQuests).length} quests to ${outJsonPath}`);

  // Generate vaultQuests.ts wrapper
  const outTsPath = path.resolve(process.cwd(), 'src/data/vaultQuests.ts');
  const tsContent = `// Auto-generated by scripts/build-quests.ts from Obsidian Vault
import rawQuests from './vaultQuests.json';

export interface VaultQuest {
  id: string;
  title: string;
  giver: string;
  category: string;
  description: string;
  walkthrough: string[];
  rewards: string[];
  connections: string[];
  rawPath: string;
}

export const VAULT_QUESTS: Record<string, VaultQuest> = rawQuests as Record<string, VaultQuest>;

export function getVaultQuest(id: string): VaultQuest | undefined {
  return VAULT_QUESTS[id];
}
`;
  fs.writeFileSync(outTsPath, tsContent, 'utf-8');
  console.log(`[Quest Compiler] Successfully wrote TypeScript export to ${outTsPath}`);
}

main();
