// Auto-generated by scripts/build-quests.ts from Obsidian Vault
import rawQuests from './vaultQuests.json';

export interface VaultQuest {
  id: string;
  title: string;
  giver: string;
  category: string;
  description: string;
  walkthrough: string[];
  rewards: string[];
  connections: string[];
  rawPath: string;
}

export const VAULT_QUESTS: Record<string, VaultQuest> = rawQuests as Record<string, VaultQuest>;

export function getVaultQuest(id: string): VaultQuest | undefined {
  return VAULT_QUESTS[id];
}
